---
- hosts: all
  tasks:
    - name: run container
      docker_container:
        name: jenkins
        image: registry.gitlab.com/tmobile/dig-card/firefly/jenkins:{{ jenkins_docker_container_sha }}
        state: started
        hostname: "{{ jenkins_hostname }}"
        restart: yes
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /opt/apps/jenkins_home:/var/jenkins_home
        env:
          JENKINS_OPTS: --prefix=/jenkins
          TZ: America/Chicago
        tags:
          - jenkins
