version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: cicdmojo.live
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "8000:80"
      - "8822:22"
    volumes:
      - /opt/apps/cicdmojo/gitlab/config:/etc/gitlab
      - /opt/apps/cicdmojo/gitlab/logs:/var/log/gitlab
      - /opt/apps/cicdmojo/gitlab/data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - /opt/apps/cicdmojo/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
