version: '3.5'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: bebop.network
    restart: unless-stopped
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 8822
    ports:
      - "8000:80"
      - "8822:22"
    volumes:
      - /opt/apps/cofeit/gitlab/config:/etc/gitlab
      - /opt/apps/cofeit/gitlab/logs:/var/log/gitlab
      - /opt/apps/cofeit/gitlab/data:/var/opt/gitlab
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    depends_on:
      - gitlab
    volumes:
      - /opt/apps/cofeit/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab

networks:
  gitlab:
